### PR TITLE
OTP Automation and relogin after 15 minutes

### PR DESCRIPTION
**Pull request by akzarma**
One can use IFTTT (android) to set up a trigger when OTP is received and then update the google sheet cell (cell number: A1)

image
also added a field for linking the google sheet with extension

### CODE REVIEW

**Comment by akzarma** [comment]
This PR needs some refactoring tho. This week a bit busy with other priorities. will take a look at the weekend.

**Comment by sushrut111** [comment]
@akzarma 
I appreciate your efforts and you have found a really great solution. 👏 

However this extension was born for a reason - if you go through the readme:

```
Many other developers have created scripts to book vaccine slots automatically - due to this, those who do not know how to use those scripts are facing issues while searching for vaccine slots. I made this extension to counter that - anyone will be able to use this extension very easily even if they do not know how it works. I am not charging anything for this - this will be FREE of cost forever. I also have created support channel to help people use this extension if they have difficulties.

Because everyone has equal right to get vaccinated on time!
```

This integration is not very friendly to those who do not understand it - and this is going to other way you see?

I would love your contribution to this project - the auto logout feature you added is awesome. Why don't you start another PR to add it and I will merge it.

**Comment by prayuj** [comment]
@akzarma 
Really good work on the integration with IFTTT, I for one am interested in all things IOT. That being said, and as @sushrut111 has mentioned, the motivation behind this project was to help the masses, majority of whom will not be able to use this feature and will give an unfair to advantage to the ones that can!

**Comment by AshishNamdev** [comment]
@sushrut111 , @prayuj  We can still have this feature as an **optional feature** for the ones who are familiar with IFTTT setup and can use this functionality.

**Pull request closed without merging**
