### PR TITLE
Updated CHANGELOG.md with v4.0.3

### PR DESCRIPTION
**Pull request by azimb**

### CODE REVIEW

**Comment by sushrut111** [comment]
The format is incorrect.
If you are doing it manually, stop there!
https://github.com/rhysd/changelog-from-release#:~:text=changelog%2Dfrom%2Drelease%20is%20a,generated%20from%20the%20releases%20page.

Use this and update.

**Comment by azimb** [comment]
I use macOS but can't find a binary for it here:
https://github.com/rhysd/changelog-from-release

can't use this tool on macOS, correct?

**Comment by sushrut111** [comment]
I work on mac.
That's okay, I will update the changelog later. You can pick some other issue if you would like to.

**Comment by sushrut111** [comment]
I have go installed. I could just "go get" and work it out. You can try that sometime later.

**Comment by azimb** [comment]
While doing it manually, it looks like I forgot to add the GitHub version compare link at the bottom.

Anyway, thanks, I didn't realize I could build the tool from source and do it.

**Comment by sushrut111** [comment]
No worries @azimb 
Thanks for your efforts! I appreciate it!

**Pull request closed without merging**
