### PR TITLE
jQuery to Toggle Modal

### PR DESCRIPTION
**Pull request by prayuj**
Use jQuery to toggle modal
renamed shortcut file to event listeners

### CODE REVIEW

**Comment by prayuj** [comment]
@sushrut111 , can you confirm if this fix works on kiwi?

**Comment by sushrut111** [comment]
I have fixed this already in : https://github.com/sushrut111/cowin-automation-extn/pull/14

**Comment by sushrut111** [comment]
@prayuj close this PR once you see the comment above!

**Comment by prayuj** [comment]
It seemed better to move all the toggling to a separate file instead of having bootstrap data attributes handling it. It would have been easier for future contributors to work on it if necessary. 
Anyway we can take a look at it in the future

**Pull request closed without merging**
