### PR TITLE
added options for auto redirect/beep on session timeout.

### PR DESCRIPTION
**Pull request by tejas-LXIX**
Added the option to enable the user to choose whether he wants to be redirected to the homepage automatically after session timeout or not. Redirects to the "enter phone number" page autoRedirectCheckbox is checked. Otherwise, gives a "confirm" box to the user if autoRedirect set to 0.
Also,enabled the option for the user to select whether he wants a session timeout notification beep or not.
I have tested it myself and it seems to work properly.

### CODE REVIEW

**Comment by tejas-LXIX** [comment]
Solves the issues described here. https://github.com/sushrut111/cowin-automation-extn/issues/57

**Comment by sushrut111** [comment]
Before I check, can you please merge main branch into yours?
I have updated some logic for beep.

Also, I was thinking it would be a lot to add any more inputs in the form. From the feedback I received, it is already confusing some people. 

We could have something like advanced options and by default have the voice notification enabled which tells that session is expired. The advanced options will be visible only when they click on it and for now let keep the auto logout checkbox in advanced options. 

What do you think @prayuj ?

**Comment by tejas-LXIX** [comment]
My main branch is concurrent with yours. I have just made a few changes in the beep logic which make sure that the beep plays repeatedly if the user refuses to log in again.

Yes, that's a good idea. Keeping it in advanced options would reduce the clutter and make it easire to use.

**Comment by sushrut111** [comment]
I see that you changed the audio file path that I had kept. I have removed beep if you haven't already checked.

**Comment by tejas-LXIX** [comment]
Okay I have corrected that. Anything else?

**Comment by sushrut111** [comment]
I will review this tomorrow. I hope you have considered the things I suggested in the comments above.

**Comment by tejas-LXIX** [comment]
Yes yes, I have considered your points. It might take me some time to work on them though as I have exams coming up.

**Comment by sushrut111** [comment]
No worries. Let's see when we can tale it forward later. All the best for your exams!!

**Comment by prayuj** [comment]
Yes I agree, we can place those check boxes in a collapsible "Advanced Options" which users can then configure if needed. Also could you rename your branch, I am not able to checkout to it!

**Comment by sushrut111** [comment]
@prayuj  you can do
```
git fetch origin pull/68/head:pr68
```
on my repo.

**Comment by prayuj** [comment]
> 
> 
> @prayuj you can do
> 
> ```
> git fetch origin pull/68/head:pr68
> ```
> 
> on my repo.
> A new branch will be created with name pr68 and you can check it out.

Yup that worked, thanks!

**Pull request closed without merging**
